# Generated by Django 5.0 on 2024-08-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
